uwsgi:
    plugins: python3
    virtualenv: /home/vagrant/workshop/venv
    master: true
    uid: www-data
    gid: www-data
    socket: /tmp/workshop.sock
    chmod-socket: 666
    pythonpath: /home/vagrant/workshop
    mount: /workshop=server:app
    manage-script-name: true
    processes: 1
    enable-threads: true
    protocol: uwsgi
    need-app: true
    catch-exceptions: true
    py-auto-reload: 0
    #logto: /var/log/uwsgi/%n.log


